# Generated by Django 6.1.1 on 2026-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default='Drama', max_length=50),
            preserve_default=False,
        ),
    ]
